version: '2'
services:
  ark:
    build: .
    restart: never
    tty: true
    network_mode: host
    cpuset: "0-7"
    volumes:
      - ./data:/home/steam
      - ./bootstrap:/bootstrap
    ulimits:
      nproc: 100000
      nofile:
        soft: 100000
        hard: 100000
