version: '2'
services:
  ark:
    build: .
    tty: true
    restart: on-failure
    network_mode: host
    cpuset: '0-7'
    stop_grace_period: 10m
    stop_signal: SIGTERM
    volumes:
      - ./data:/home/steam
      - ./bootstrap:/bootstrap:ro
    ulimits:
      nproc: 100000
      nofile:
        soft: 100000
        hard: 100000
